/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['a[_ngcontent-%COMP%] {\r\n  &.close-popup {\r\n    font-size: 42px;\r\n    float: right;\r\n    color: #fff !important;\r\n    text-decoration: none;\r\n    margin: 0 30px 0 0;\r\n    cursor: pointer;\r\n    position: absolute;\r\n    top: 20px;\r\n    right: 0;\r\n  }\r\n\r\n  &.external-url-image {\r\n    font-size: 33px;\r\n    float: right;\r\n    color: #fff !important;\r\n    text-decoration: none;\r\n    margin: 0 30px 0 0;\r\n    cursor: pointer;\r\n    position: absolute;\r\n    top: 28px;\r\n    right: 0px; // setted dinamically by Angular\'s Directives\r\n  }\r\n\r\n  &.download-image {\r\n    font-size: 33px;\r\n    float: right;\r\n    color: #fff !important;\r\n    text-decoration: none;\r\n    margin: 0 30px 0 0;\r\n    cursor: pointer;\r\n    position: absolute;\r\n    top: 28px;\r\n    right: 0px; // setted dinamically by Angular\'s Directives\r\n  }\r\n\r\n  &.custom-button {\r\n    font-size: 33px;\r\n    float: right;\r\n    color: #fff !important;\r\n    text-decoration: none;\r\n    margin: 0 30px 0 0;\r\n    cursor: pointer;\r\n    position: absolute;\r\n    top: 28px;\r\n    right: 0px; // setted dinamically by Angular\'s Directives\r\n  }\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvanVhbmovRGVza3RvcC9wcm9qZWN0cy9hbmd1bGFyLW1vZGFsLWdhbGxlcnkvc3JjL2NvbXBvbmVudHMvdXBwZXItYnV0dG9ucy5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2p1YW5qL0Rlc2t0b3AvcHJvamVjdHMvYW5ndWxhci1tb2RhbC1nYWxsZXJ5L3NyYy9jb21wb25lbnRzL3VwcGVyLWJ1dHRvbnMuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
