/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.ng-gallery[_ngcontent-%COMP%] {\r\n  width: 100%;\r\n  display: inline-block;\r\n}\r\n\r\nimg[_ngcontent-%COMP%] {\r\n  &.ng-thumb {\r\n    height: 50px;\r\n    float: left;\r\n    display: block;\r\n    cursor: pointer;\r\n    margin: 2px 2px 0 0;\r\n  }\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvanVhbmovRGVza3RvcC9wcm9qZWN0cy9hbmd1bGFyLW1vZGFsLWdhbGxlcnkvc3JjL2NvbXBvbmVudHMvZ2FsbGVyeS5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2p1YW5qL0Rlc2t0b3AvcHJvamVjdHMvYW5ndWxhci1tb2RhbC1nYWxsZXJ5L3NyYy9jb21wb25lbnRzL2dhbGxlcnkuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
